### ISSUE TITLE
Support updating Hyperdisk IOPS and throughput in Compute SDK

### ISSUE THREAD

**Issue by qooiprww** [googleapis/google-cloud-java#10006]
We want to modify the IOPS and throughput parameters of the hyperdisks using the Java Compute SDK. While we've come across [documentation](https://cloud.google.com/compute/docs/disks/modify-hyperdisks#rest) for achieving this via the REST API, we haven't been able to find any Java SDK documentation covering this topic. Could you let us know whether the Java SDK supports this operation? If it does, could you link us to the documentation? Otherwise, do you have an expected date for supporting this operation in the SDK?

**Comment by blakeli0** [comment]
I don't think this feature is supported in any SDKs yet and we don't have a expected date on SDK side. The Compute team would need to support it first then we can add the functionality in the SDKs. Can you please submit a feature request in the [support console](https://cloud.google.com/support/) instead of filing on GitHub? Which should ensure a timely response from the Compute team.
