### ISSUE TITLE
Authentication error when using a regional endpoint

### ISSUE THREAD

**Issue by Pzdrs** [googleapis/google-cloud-java#10361]
Hello,
I'm encountering the same issue described in this [issue ](https://github.com/googleapis/google-cloud-dotnet/issues/8798)from the C# speech SDK.

I create my speech client using my JSON file credentials. Using the default endpoint - `speech.googleapis.com`, everything works. Though when I specify a regional API endpoint, I get the following error message
`UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.`
```
GoogleCredentials googleCredentials = ServiceAccountCredentials.fromStream(new FileInputStream(ResourceUtils.getFile("classpath:google-credentials.json")));
var speech = SpeechClient.create(SpeechSettings.newBuilder()
                .setCredentialsProvider(FixedCredentialsProvider.create(googleCredentials))
                        .setEndpoint("europe-west4-speech.googleapis.com:443") // without this line, everything works
                .build());
```

I'm unsure whether this is a bug like with the C# SDK, or just user error.

**Comment by suztomo** [comment]
Thank you for the report. Would you share the document you followed to use europe-west4-speech.googleapis.com:443?

**Comment by Pzdrs** [comment]
I used [this](https://stackoverflow.com/questions/77076285/google-speech-v2-expected-resource-location-to-be-global-but-found-europe-wes) StackOverflow question to figure out why I couldn't access my Recognizer - I had to set the regional endpoint, because I was getting the `Expected resource location to be global error`. I assume the URL is correct, considering that if I misspell any part of it, I will get a service not found or something in that sense. [Here](https://cloud.google.com/java/docs/reference/google-cloud-speech/latest/com.google.cloud.speech.v2.SpeechSettings) it says the default port is 443. After specifying the endpoint, I got an error that the required schema is `<address>:<port>`. I assume the code was looking for a semicolon to split by, so I added the port there. Port 444 did nothing, so again, my *assumption* is that nothing is listening on it, thus 443 must be the right one.

**Comment by suztomo** [comment]
> why I couldn't access my Recognizer

Would you share the document that guided you how to use Recognizer? That document should have guidance on how to set an endpoint.

**Comment by Pzdrs** [comment]
Uh, I pretty much just looked at the REST docs and looked for methods that set the required params in the source code.

**Comment by suztomo** [comment]
Thanks. From https://cloud.google.com/speech-to-text/docs/endpoints both URL and the content, I don't find it's specific to v1. What made you think it's for v1?

**Comment by Pzdrs** [comment]
![image](https://github.com/googleapis/google-cloud-java/assets/57369536/0085873f-5b5f-46a1-a262-c05073e39adb)
The fact that the "version dropdown" has the v1 selected. I might be wrong, as this is my first time using the Google docs and services.

**Comment by suztomo** [comment]
Thank you. Will respond later this week.

**Comment by lqiu96** [comment]
Hi, I took a look at the C# issue and I believe I've seen the missing scopes issues before. I believe the client library has additional logic internally for adding some scopes to the credentials when using the client libraries. Since you're creating the GoogleCredentials yourself, I think you'll need to manually add in some default scopes for Speech: https://github.com/googleapis/google-cloud-java/blob/b4ec2449f092e6dca1c9cd169421311579b67777/java-speech/google-cloud-speech/src/main/java/com/google/cloud/speech/v1/stub/SpeechStubSettings.java#L97-L99

Could you try something like this:
```
    GoogleCredentials googleCredentials = ServiceAccountCredentials.fromStream(new FileInputStream("{SA_KEY_LOCATION}"));
    googleCredentials = googleCredentials.createScoped(scopes);
    ServiceAccountCredentials serviceAccountCredentials = (ServiceAccountCredentials) googleCredentials;
    serviceAccountCredentials = serviceAccountCredentials.createWithUseJwtAccessWithScope(true);
    var speechClient = SpeechClient.create(SpeechSettings.newBuilder()
            .setCredentialsProvider(FixedCredentialsProvider.create(serviceAccountCredentials))
            .setEndpoint("eu-speech.googleapis.com:443")
            .build());
```
and let me know if that works or not?

I think a possible cleaner version with the google-auth-library is to let the client library find the credentials for you. Following the logic for ADC: https://github.com/googleapis/google-cloud-java/blob/b4ec2449f092e6dca1c9cd169421311579b67777/java-speech/google-cloud-speech/src/main/java/com/google/cloud/speech/v1/stub/SpeechStubSettings.java#L97-L99

Try setting the `GOOGLE_APPLICATION_CREDENTIALS` env var and remove the `setCredentialsProvider` call from the SpeechSettings Builder. I think it should work properly and hook into our additional logic for adding scopes. Let me know if that works or not.

**Comment by lqiu96** [comment]
Glad to hear that it works by adding in scopes and/or using ADC. We will be looking to try and enhance our docs + error message(s) where possible so it is clearer as to what went wrong.

We do have a small section on authentication here: https://github.com/googleapis/google-cloud-java/?tab=readme-ov-file#authentication which may help you if you have any future auth problems.

**Comment by Pzdrs** [comment]
Yeah, adding scopes worked. For a first-time Google Cloud user, the Javadoc is lacking in my opinion and the errors are not very descriptive, but the quick feedback I've gotten here definitely made up for it. I'll totally give the whole README a read, just by a quick glance it looks like there is a lot to learn from it.

Thank you

**Comment by lqiu96** [comment]
> For a first-time Google Cloud user, the Javadoc is lacking in my opinion and the errors are not very descriptive

Acknowledged. Thank you for your feedback. We will work to improve both of these.
