### ISSUE TITLE
Breaking changes are labeled as Feature changes in the library-specific CHANGELOG

### ISSUE THREAD

**Issue by burkedavison** [googleapis/google-cloud-java#10844]
Breaking changes in the root CHANGELOG are only 'Feature' changes in the client library's CHANGELOG.

![image](https://github.com/googleapis/google-cloud-java/assets/40617934/349ffffc-d20b-4691-aced-352608d610a7)
vs
![image](https://github.com/googleapis/google-cloud-java/assets/40617934/bb495755-ad91-4154-8bf0-3908e7e552ba)

**Comment by blakeli0** [comment]
Looks like we are grouping all changes into either `features` or `dependencies` in the [scripts](https://github.com/googleapis/google-cloud-java/blob/main/.github/release-note-generation/split_release_note.py#L111-L119), was this by design @suztomo?

Separately, the duplicated entry is because of the duplicated entries in [release notes](https://github.com/googleapis/google-cloud-java/releases/tag/v1.37.0), which is still an issue but should probably be tracked differently.

**Comment by suztomo** [comment]
I didn't incorporate the breaking change section as it's rare. I think this issue and desire to enhance it are valid.

**Comment by suztomo** [comment]
Looking into this.
