### ISSUE TITLE
`com.google.cloud.core.ServiceOptions.getDefaultProjectId()` does not work in App Engine local environment

### ISSUE THREAD

**Issue by jabubake** [googleapis/google-cloud-java#2209]
APIs like `google-cloud-pubsub` require users to explicitly provide a project id. 
When [App Engine Maven Plugin](https://github.com/GoogleCloudPlatform/app-maven-plugin) is used to run locally using `mvn appengine:run` 
 `ServiceOptions.getDefaultProjectId()` returns `no-app-id` unless 
`<application>project-id</application>` exists in `appengine-web.xml`

Note : returns project-id without the application entry when deployed to App Engine.

@ludoch @lesv

**Comment by lesv** [comment]
Ideally, when running locally on GAE std, you'll try to grab from either `GOOGLE_CLOUD_PROJECT`, if defined, or (typical case), get it from `gcloud`.

**Comment by garrettjonesgoogle** [comment]
This appears to be a problem even with clients trying to load project ID implicitly, e.g. BigQuery (user-filed issue: https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2235 )

**Comment by neozwu** [comment]
Our current approaches to retrieving project/application id fail when using gcloud sdk maven plugin and when application id is not specified in appengine-web.xml.  I have filed an [issue](https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/202) to app-maven-plugin. On a different note, based on appengine runtime contract, both `GCLOUD` (deprecated) and `GOOGLE_CLOUD_PROJECT` Env Vars should be injected to app engine runtime container.  However, I'm not seeing any of these (for both local or remote servers). I'm tracking this issue with runtime team.

**Comment by chanseokoh** [comment]
> Our current approaches to retrieving project/application id fail when using gcloud sdk maven plugin and when application id is not specified in appengine-web.xml.

This happens regardless of the maven plugin. For example, where and how will you get an application ID if a project doesn't use any build system? In such a case, users will run the local server directly at the command-line (which is what [the Eclipse plugin](https://github.com/GoogleCloudPlatform/google-cloud-eclipse) does, for example.)

I also left some comment in the maven plugin issue: https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/202#issuecomment-318209862

**Comment by neozwu** [comment]
@chanseokoh thank you for your reply on this.  The information (project/application id) is actually there (in gcloud sdk). Since this is a gcloud sdk-based plugin, I thought it would retrieive a project id when running "mvn appengine:run".  I think "mvn appengine:deploy" by default does this - using the project id set by "gcloud init" as the `project` property. What is the design idea behind this asymmetry ?

**Comment by chanseokoh** [comment]
The Maven plugin is not the only tool that is Cloud SDK-based. For example, the Eclipse plugin and the IntelliJ plugin run "gcloud app deploy" (under the hood) like this:

$ gcloud app deploy app.yaml ... --project &lt;project ID where you want the app to be deployed> ...

As you can see, the project ID does not come from "gcloud init" but from the argument explicitly given. In other words, the project ID is part of a _deploy configuration_, which is available (and only needed) at the time of deployment. We ask Eclipse/IntelliJ users to which projects they want their apps to deploy. It does not make sense for users to go out of an IDE and do "gcloud init" to designate which projects an app should be deployed.

So, even if the Maven plugin (and [the Gradle plugin](https://github.com/GoogleCloudPlatform/app-gradle-plugin)) populated and set a project ID configured by "gcloud init", it will not solve the problem for IDE users. (Remember that this user hitting this problem is using the Eclipse plugin: https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2235). You need a more fundamental solution to this problem.

**Comment by chanseokoh** [comment]
> In such a case, users will run the local server directly at the command-line (which is what the Eclipse plugin does, for example.)

Also, don't forget the case where users don't use any tool (not even gcloud) but directly invoke the dev server at the command-line.

`$ java ... -Dappengine.sdk.root=... -cp .../appengine-tools-api.jar com.google.appengine.tools.development.DevAppServerMain --port=8080 <some app directory>`

We need a solution to avoid the problem in this case too.

**Comment by chanseokoh** [comment]
Have you reached any resolution? I am very curious. If not, please update later when you come up with one. Whatever it will be, I can anticipate many problems as long as the dev server wants to know some project ID. Ideally, the dev server should just not need it.

**Comment by lesv** [comment]
I asked for a feature in GoogleCloudPlatform/appengine-plugins-core#439 to set it.  It would still be nice if you picked up GOOGLE_CLOUD_PROJECT or .config/gcloud/configurations/config_[.config/gcloud/active_config] and grab "project = " from it.

**Comment by sduskis** [comment]
This issue seems a bit stale.  This is also not actionable in this repository.  GoogleCloudPlatform/appengine-plugins-core#439 is open, so I'm going to close this PR.
