### ISSUE TITLE
Fix ITStorageTest credentials

### ISSUE THREAD

**Issue by andreamlin** [googleapis/google-cloud-java#3136]
When a user runs `ITStorageTest.testGetServiceAccount()`, they fail with the message 
```
ITStorageTest.testGetServiceAccount:1678 expected:<[gcloud-devel]@gs-project-accounts...>
  but was:<[REDACTED]@gs-project-accounts...>
```

Deliverables:
1. Remove the `gcloud-devel` hardcoded project value from the test file. 
2. Project ID needs to be configurable for this test, perhaps via [GOOGLE_APPLICATION_CREDENTIALS](https://cloud.google.com/docs/authentication/production).

**Comment by hzyi-google** [comment]
@andreamlin Are you ok if I make the test checks the return value is not null?

I am observing the following behavior which makes this tests a little tricky:
If I am using a personal google cloud project, the service account returned is the `client_email` specified in the json file.
However if I am using the `gcloud-devel` project, the service account returned is the hard-coded value. (I guess because everyone on our team is using the same service account?)

This method fetches service account from server, as long as the returned code is 200, I think we can consider this test a pass. What do you think?

**Comment by chingor13** [comment]
I believe this is fixed as users can run the integration tests with default credentials.
