### ISSUE TITLE
should be able to change hostname of generated URL

### ISSUE THREAD

**Issue by yogeshpatilcrest** [googleapis/google-cloud-java#3140]
We are facing google storage access issue in China. We have a kind of proxy controller at our CDN (Fastly) which will serve files from google storage to avoid Chinese blockage of Google hostnames. 
So I need CDN's host in resource URL instead of `storage.googleapis.com`. I checked code and found it is currently hardcoded in `StorageImpl.signUrl(...)`. So it would be good if it is possible to configure it.
Currently, URL looks like: https://storage.googleapis.com/<bucket>/<file_path>?GoogleAccessId=accessID
And I want something like: https://my.custom.host.com/<bucket>/<file_path>?GoogleAccessId=accessID

**Comment by chingor13** [comment]
Fixed in #3910

**Comment by houglum** [comment]
A question popped up regarding this functionality on PR #6183.

As far as I can tell, [our CNAME docs](https://cloud.google.com/storage/docs/request-endpoints#cname) and all CDNs (including fastly) suggest that you should point your CNAME or CDN alias at `<bucket_name>.storage.googleapis.com`, which uses virtual-hosted-style URLs (meaning the bucket is supplied in the hostname, rather than in the path portion of the URL).  

However, this code is producing path-style URLs (that include the bucket in the path portion of the URL instead), which wouldn't work if you followed those instructions... e.g. it would produce something like `https://my.custom.host/mybucket/myobject...`, instead of `https://my.custom.host/myobject`.

I'd like to **fix** this, but I don't want to break anyone if they're depending on some other undocumented routing/proxying behavior. @yogeshpatilcrest could you confirm that when you supply this option, you expect the bucket to be in the path portion of the URI? If so, could you provide me with an example URL so I can look into how the routing/host logic works?
