### ISSUE TITLE
[BigQuery] FieldValue.getTimestampValue returns incorrect microseconds

### ISSUE THREAD

**Issue by martinstuder** [googleapis/google-cloud-java#3356]
I have a BigQuery table with a timestamp column where some values are '9999-12-31 23:59:59.999 UTC' (no microseconds; i.e. `TIMESTAMP_TO_USEC` of that timestamp gives 253402300799999000). Retrieving such a timestamp using the Java BigQuery API (via `FieldValue.getTimestampValue`) results in 253402300799999008 being returned, i.e. with an additional 8 microseconds. I haven't seen this for other timestamp values yet.

**Comment by martinstuder** [comment]
Ok, that does explain what's going on. It seems odd to me though to serialize a TIMESTAMP that way. Is there any particular reason for not serializing the usec directly and doing `Long.valueOf(getStringValue()).longValue()`?

**Comment by shollyman** [comment]
This does seem an odd representation in hindsight, which comes from BigQuery's initial public release period back in 2012 when this was a more common way of representing timestamps in web APIs.  Its remained in this form to maintain compatibility for existing callers, as we'd want to change something like this with a major API revision, which hasn't occurred since that period.
