### ISSUE TITLE
Illegal Reflective Access in Java 10

### ISSUE THREAD

**Issue by jrdoane** [googleapis/google-cloud-java#3729]
When using `[com.google.cloud/google-cloud "0.47.0-alpha"]` in Clojure `[org.clojure/clojure "1.9.0"]` using `openjdk version "10.0.2" 2018-07-17`, when my application starts, I receive the following warnings from the JVM:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.grpc.netty.shaded.io.netty.util.internal.ReflectionUtil (file:/usr/local/bin/lrm-logging-service.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.grpc.netty.shaded.io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

The project producing this error is using the following class imports from the Google Cloud library:

`com.google.cloud.datastore`: `Key KeyFactory Datastore DatastoreOptions`
`com.google.cloud.logging`: `Logging Logging$WriteOption LoggingOptions LogEntry Payload Payload$JsonPayload`
`com.google.cloud`: `MonitoredResource`

**Comment by elharo** [comment]
That's a really old version. Can you try in 0.62.0-alpha and see if it still happens?

**Comment by jrdoane** [comment]
The latest version in Maven Central is `0.42.0-alpha` which is why I'm using it. I'm using the artifact link described in the README. Is this not the correct one to be using?
https://search.maven.org/search?q=g:com.google.cloud%20a:google-cloud

**Comment by jrdoane** [comment]
I also tried using these two dependencies instead of the `0.42.0-alpha` for the "all-in-one" artifact with the same result:
`[com.google.cloud/google-cloud-datastore "1.45.0"]`
`[com.google.cloud/google-cloud-logging "1.45.0"]`

**Comment by elharo** [comment]
Off the top of my head, I'm not sure what the com.google.cloud:google-cloud artifact is. Wherever it comes from, it hasn't been updated since May. If 1.45.0 is failing, we probably need to take a look at this. I'm not sure what our official stance on Java 9 and 10 support is.

It looks like the issue comes from deep inside Netty:

WARNING: Please consider reporting this to the maintainers of io.grpc.netty.shaded.io.netty.util.internal.ReflectionUtil

so that's where the initial fix needs to go followed by an upgrade to our dependency here.
