### ISSUE TITLE
PubSub : add source projectId, topic and subscription to PubsubMessage

### ISSUE THREAD

**Issue by dhoard-papajohns** [googleapis/google-cloud-java#3816]
Some use cases require that source (projectId, topic and subscription) of a PubsubMessage ... yet the message doesn't have this information.

Added this should at the server shouldn't cause any issues as it's adding data to the message.

**Comment by ajaaym** [comment]
@dhoard-papajohns Application already has this information about projectId, topic and subscription. It can wrap the incoming PubsubMessage with this information rather than adding to PubsubMessage which is proto object, even if we add to PubsubMessage then this same information would be transferred over wire which is not efficient. So it makes sense for application to wrap PubSubMessage with other information in to object of their choice.

**Comment by dhoard** [comment]
@ajaaym please close.  I agree, we do not want to change the proto object because of performance issues.

It's unfortunate that `PubsubMessage` is a proto object and wasn't abstracted / wrapped by another interface / object paradigm.
