### ISSUE TITLE
Pub/Sub ApiFutures.addCallback() deprecated

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/google-cloud-java#3861]
What should people use to add an asynchronous callback on the Api Futures instead now since it's deprecated? 

https://github.com/googleapis/google-cloud-java/blob/9cc799fcf68c82ab431d425fefa58ef615ce8e5b/google-cloud-examples/src/main/java/com/google/cloud/examples/pubsub/snippets/CreateTopicAndPublishMessages.java#L103

**Comment by vam-google** [comment]
You can use

```java
ApiFutures.addCallback(final ApiFuture<V> future, final ApiFutureCallback<? super V> callback, Executor executor)
```
To get identical behavior to the deprecated method, pass guava's `com.google.common.util.concurrent.MoreExecutors.directExecutor()`, but please do not do it unless  you really know what you are doing. It is better to use separate thread executor, because using direct executor will execute the callback under future's internal locks and may break its behavior if the callback is not properly implemented.

**Comment by anguillanneuf** [comment]
Thank you. I see the file now: 

https://github.com/googleapis/api-common-java/blob/master/src/main/java/com/google/api/core/ApiFutures.java

We should update this sample because it is linked to our docs.
