### ISSUE TITLE
Bigtable: There should be versions of readRowAsync() and readRowsAsync() that takes a Query as argument

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/google-cloud-java#4053]

**Comment by igorbernstein2** [comment]
@emmmile did you specifically want to take a `Query`? or would adding an override that takes a filter be ok? I'm hesitant for point reads to take a Query because Query represent  multiple row ranges and keys so it feels wrong to use that for point reads

**Comment by emmmile** [comment]
So right now we have (excluding the `ByteString` alternatives): 
- `Row readRow(String, String)`
- `ServerStream<Row> readRows(Query)`
- `ApiFuture<Row> readRowAsync(String, String)`
- `void readRowsAsync(Query, StreamObserver)`

My main problem if I recall correctly was with the last one, because I just wanted a version that returns something like the others, so something like:

- `ApiFuture<List<Row>> readRowsAsync(Query)`

Then for the point lookup I'm not sure if `Query` is the right abstraction, I think `Filter` is good too. The main thing for us was to be able to specify filters like `cellsPerRow()` and `cellsPerColumn()` for example. So something like:

- `Row readRow(Filter)`
- `ApiFuture<Row> readRowAsync(Filter)`

**Comment by balaji** [comment]
@emmmile Yes that is helpful.

At the moment we do this:

`this.bigTableClient.readRowsCallable().first().futureCall(query);` to get a row and if we replace `.first()` with `.all()` we get a list of rows. It would be nice to abstract this.

**Comment by balaji** [comment]
@igorbernstein2 yes. 👍
