### ISSUE TITLE
Java async pull subscriber stops receiving messages

### ISSUE THREAD

**Issue by sholavanalli** [googleapis/google-cloud-java#4205]
#### Environment details

- OS: ubuntu0.18.04.1-b12
- Java version: openjdk version "1.8.0_191"
- google-cloud-java version(s): 1.40.0

#### Steps to reproduce

Java async pull subscriber abruptly stops pulling messages. 

#### Code snippet

Flow control settings:

```java
    FlowControlSettings flowControlSettings = 
        FlowControlSettings.newBuilder()
        .setMaxOutstandingElementCount(10000)
        .setMaxOutstandingRequestBytes( 640000 ).build();
```

**Comment by chrisribble** [comment]
We have had the same problem where messages stop being pulled. We have worked around it by tracking all new messages and shutting down/restarting the Subscriber (via a background thread) if we have no received a new message before some timeout elapses. My main loop then starts a new Subscriber and background thread once the Subscriber hit the TERMINATED state (this ends up being the core of what our main loop does).

However, that has its own problems as occasionally the Subscriber fails to reach the TERMINATED state. I'm not sure if there is some new system behavior or if I've just started getting more unlucky or whether the upgrade of the pubsub library from 1.43.0 to 1.49.0 triggered this behavior. However, I am about to rewrite this code path in my applications again so that I control the signal path more directly when we detect the Subscriber is "stuck" so that I don't block on subscriber.awaitTerminated() to trigger setting up the Subscriber again.

It would be nice if the underlying issue (the Subscriber stops accepting new messages eventually) were fixed so that all of this were not necessary.

**Comment by sholavanalli** [comment]
@chrisribble I saw this issue happen a lot of times between Dec 7th to 10th. I've not seen this happen again there after.

**Comment by chingor13** [comment]
We had a backend bug where the server could incorrectly return a UNAUTHORIZED exception which is not retried by the Subscriber. In this case the subscriber would be put in the FAILED state and would still be running, but the streaming connection would be stopped.

The backed fix for the unauthorized bug is fixed/rolling/rolled out as of yesterday, but we still need better visibility or examples of how to handle these cases.

**Comment by dhoard** [comment]
@chingor13 did the backend bug affect synchronous pull requests as well?

**Comment by lmuhlha** [comment]
Using the listener, is there an example of restarting the subscriber with some kind of exponential backoff to catch these types of issues?

Reading the doc string:
"* Called when the service transitions to the {@linkplain State#FAILED FAILED} state. The
     * {@linkplain State#FAILED FAILED} state is a terminal state in the transition diagram.
     * Therefore, if this method is called, no other methods will be called on the {@link Listener}."

Would it be possible to recover from a failed state like this?

```
      subscriber.addListener(
          new Subscriber.Listener() {
            @Override
            public void failed(Subscriber.State from, Throwable failure) {
```

**Comment by ajaaym** [comment]
@sholavanalli for async pull, hoping that you are using pullCallable, can you please wrap that in to try catch block and retry for exception? Please see example [#4220](https://github.com/googleapis/google-cloud-java/issues/4220)

**Comment by sduskis** [comment]
This hasn't been active in a while.  If anyone has an issue like this, pleas open a new bug.
