### ISSUE TITLE
pubsub synchronous pull late acks are ignored

### ISSUE THREAD

**Issue by bruceskingle** [googleapis/google-cloud-java#4242]
It seems that acks sent after the ack timeout are ignored.

I have a subscriber based on the synchronous pull interface which naively hopes that it will complete within the ack timeout. This normally works but an unusually large message appeared which took 11 seconds to process (the ack timeout is 10 seconds). This message was being redelivered indefinitely, which seems wrong.

I accept that the message becomes redeliverable as soon as the ack timeout has expired and that it is even reasonable that pubsub may re-deliver the message after the ack has been sent (on the basis that it may already be lining up to redeliver and that process may be hard to intercept), but the ack should not, in my view, be ignored and the message should not be redelivered forever.

I am putting in code to extend the ack timeout, but I think the handling of late acks is wrong and should be changed. If the client is idempotent then a late ack would cause one or more unnecessary repeats of the work but the message would eventually be cleared without the need for manual intervention.

I am aware that the async API does this under the covers, we already moved away from that implementation for other reasons.

#### Environment details

- Java version: 8
- google-cloud-java version(s): 1.56.0

#### Steps to reproduce

1. receive a message
2. wait more than the ack deadline
3. ack the message
4. observe that the same message is redelivered, goto 2

This loop never terminates.

**Comment by kolea2** [comment]
There are two things you could look into:

1. You can update the acknowledgment deadline on the whole subscription
2. You can programmatically update the deadline using the `ModifyAckDeadline` APIs.

Alternatively, you can also look into acknowledging the message before processing. Hope this helps!

**Comment by bruceskingle** [comment]
I said that already, the point is, that even if an ack is late, it indicates that the message has been processed and should not be redelivered again and again.
I was not asking a question, I assert that this is incorrect behaviour.

**Comment by kolea2** [comment]
Unfortunately, if the ack deadline is missed, the message will get redelivered. More information on this behavior can be found here: https://cloud.google.com/pubsub/docs/subscriber#at-least-once-delivery.

**Comment by dhoard** [comment]
@kolea2 Basic tests using the gcloud command show that the (re-)delivered message gets the same ack id ... so it's reasonable to expect the last ack call to work, even though message gets delivered again.

For @bruceskingle 's case that takes 11 seconds to process, he should only receive the message two times.

This is definitely a bug.

**Comment by kolea2** [comment]
When using synchronous pull, it is up to the user to handle things like increasing the ack deadline before it expires, which can be difficult to get right. For synchronous pull, the behavior when issuing an ack after the ack deadline has expired depends on the timing of the re-delivered message and the ack from the first delivery. Assuming the ack ID has not changed, issuing the ack after the message has been redelivered a second time should be successful (although some duplicates are always possible). But if the ack arrives at the server before the message has been redelivered (even if the pull request was issued earlier but has not yet completed), the ack will fail and this will result in a duplicate. Note also that if the ack ID has changed (which can happen on a re-delivery), then the ack from the first delivery which the deadline has expired will always fail.

As the behavior described in this issue seems to be working as expected, I’m going to close this. Please feel free to reopen if you have any questions or need any clarifications. Thanks!

**Comment by bruceskingle** [comment]
"Assuming the ack ID has not changed, issuing the ack after the message has been redelivered a second time should be successful (although some duplicates are always possible). "

This is not the observed behaviour, what I see is the ack ID does not change, the message is delivered repeatedly (for ever as far as I can tell) and an ack is sent (and ignored) after every delivery, but after the ack deadline has expired.

I believe that this is not working as you described.

**Comment by kolea2** [comment]
Sorry, to clarify - there's essentially a race between the server receiving the ack and the server marking the message as re-delivered, which is why the user may need to increase the deadline. For reference, "But if the ack arrives at the server before the message has been redelivered (even if the pull request was issued earlier but has not yet completed), the ack will fail and this will result in a duplicate."

If this is not the behavior you're observing, you can file an issue against the server itself under Cloud Pub/Sub: https://cloud.google.com/support/docs/issue-trackers.
