### ISSUE TITLE
Java grpc auto tune is disabled sets transport window size to 1mb

### ISSUE THREAD

**Issue by ajaaym** [googleapis/google-cloud-java#4657]
Java grpc has auto tune transport window disabled and its default window size is 1 mb. While c grpc has auto tune enabled and adjust the initial window to around 4mb or more.

**Comment by ajaaym** [comment]
FYI @dpcollins-google

**Comment by sduskis** [comment]
@ejona86, do you have any perspective on why the gRPC Java default and the C settings would be different (as per the OP)?

**Comment by ejona86** [comment]
"Because they are different implementations."

Before 1.0 benchmarks showed a larger window (~1 MB) was necessary for proper cloud bigtable performance. Thus Java increased the default window size, as that's all there was time to do.

Later, I designed the auto tuning and it was implemented in Java. But GFE has some silly PING restrictions that require working around, so it was left disabled. C had some users complain about performance, so the auto-turning was implemented in C. C tracks GFE's state and avoids sending PINGs if it would conflict with GFE's restrictions; however, this was implemented improperly and has caused issues in the past; it may be right now. Go was last, and used a technique to "trick" (it can happen quite naturally, which is why I say the behavior was silly) GFE into resetting its PING restrictions.

But nobody has complained about Java performance or memory overhead or push-back delay (to my surprise) and there have been active fires elsewhere, so there's not been effort to finish the work. It may be that users that are impacted by these negative things are simply content with changing the window size in NettyChannelBuilder.

**Comment by sduskis** [comment]
@ejona86, thanks for the explanation.

I think we should revisit the Cloud Bigtable performance question relating to the window settings.

FYI, right now, there are concerted efforts to improve performance of Pub/Sub and we'll probably do more testing in the near future.

**Comment by ejona86** [comment]
@sduskis, I'm not sure what you're saying. Are you saying that some further performance investigations are showing the window size may need to be larger than 1 MB? Or are the problems that the current value is too large?

In either case, instead of changing the current value we'd probably need to try to enable window auto-tuning. That would start as 64 KB and increase the size as necessary (like Go and C).

**Comment by sduskis** [comment]
@ejona86, I guess there isn't something for you to do with the window size.  I guess I'm just musing out loud to see if we ought to test different window sizes in our internal tests.

I think that we shouldn't continue discussing this on `google-cloud-java`.
