### ISSUE TITLE
BigQuery swallowing exceptions

### ISSUE THREAD

**Issue by sduskis** [googleapis/google-cloud-java#4689]
Steps to reproduce:
Consider two Cloud Platform Projects "A" and "B".

1. Generated Service Account Key for Project "A" (in JSON Format) with role as BigQuery Metadata Viewer.
2. Modified the "project_id" value from "A" to "B" in the file.
3. Used this file to connect to BigQuery instance.
4. listDatasets() on com.google.cloud.bigquery.BigQuery returns an empty List.

Expected Outcome:
The operation should fail, stating cannot access Project "A" with the provided credentials.

Other Information:
Using Google Client Library: com.google.cloud:google-cloud-bigquery:jar:1.48.0

```java
        GoogleCredentials googleCredentials;
        File credentialsFile = new File("path to the service account key file");
        try(FileInputStream fileInputStream = new FileInputStream(credentialsFile)) {
            googleCredentials = ServiceAccountCredentials.fromStream(fileInputStream);
            BigQuery bigQueryClient = BigQueryOptions.newBuilder()
                    .setCredentials(googleCredentials)
                    .build()
                    .getService();
            for (Dataset dataset : bigQueryClient.listDatasets().iterateAll()) {
                // listDatasets() returns an empty list
            }
        } catch (IOException ioException) {
            // do something
        }
```

[This was reported by a user]

**Comment by ajaaym** [comment]
@sduskis server is returning empty dataset and not returning any error. This can not be fixed in client.

**Comment by sduskis** [comment]
This is similar to ##3344

**Comment by ajaaym** [comment]
@sduskis I verified all http request and response in this case and  listDataset is returning status code 200 for refresh token and listDataset api. This is same as authenticating with project A and accessing resource from project B. Changing just project id to B in json file still authenticates as A since refresh token belong to project A.

However the api we are using in this issue step is list, it just returns empty list since project B didnt grant permission to any dataset to project A.

If we use exact data set id with api ```bigQueryClient.getDataset("testdataset");``` then it returns proper error message as below.

```
com.google.cloud.bigquery.BigQueryException: Access Denied: Dataset ociinternalappid:testdataset: The user clients-dev@grass-clump-479.iam.gserviceaccount.com does not have bigquery.datasets.get permission for dataset ociinternalappid:testdataset.
```
