### ISSUE TITLE
Spanner sessions/channels recommendation needed

### ISSUE THREAD

**Issue by vineela-gampa** [googleapis/google-cloud-java#4961]
Hi Spanner team

I want to know whats the recommended configuration required for min / max sessions on spanner. whats the ideal count of grpc channels to be configured?
Current defaults used in code min =10 sesions max=400 
and grpc channels defaults to 10

Inorder to handle 100 TPS with spanner node counts=2  what is the recommended min / max sessions to be configured and channel count ?

**Comment by vineela-gampa** [comment]
@sduskis  do you have recommendation for the question posted?

**Comment by olavloite** [comment]
@vineela-gampa As always, 'it depends', but a couple of things to take into account:

1. As one session can only execute one transaction at any time, the total number of sessions should be at least the number of transactions that will execute in parallel.
2. You mention that you are running 100 transactions per second. Are all of those read/write transactions, or are some of them read-only transactions (and also defined as read-only transactions, and not as read/write transactions that only perform read operations)? The session pool of the Spanner client library will create a pool of sessions prepared for read/write transactions. You should configure the session pool in such a way that there is always a prepared read/write transaction available whenever you want to start one. Use the combination of MaxSessions and WriteSessionsFraction to ensure that you can have at least as many read/write sessions as the number of read/write transactions that will executing in parallel at any time + a buffer of approx 20%-30%. The buffer is intended to have a number of sessions that the SessionPool at any time can prepare for read/write transactions, while other sessions are executing transactions.
3. The WriteSessionsFraction should be comparable to the actual percentage of read/write transactions that you are executing. Once again: Read/write transactions that happen to only execute read operations, count as read/write transactions. (You should always try to avoid using read/write transactions whenever you know that you will only be reading, as read/write transactions will create locks server side and read-only transactions will not create any locks.)

How many and what kind of statements are you executing in one transaction?

**Comment by vineela-gampa** [comment]
@olavloite Thanks for responding . This really helps.

In our load tests we currently run with 100 users each firing request of 1 , wait 3-5s randomly and fire next set of requests. So on an average we are running 86-100 TPS . Its purely readTransactions and there are <1% writes (outisde of load test , from users who are using the environment)

I was reading the code after i read your comments , totally depicts the code.But am unable to understand few of our tests with the behaviour we got.

How can spanner handle 100TPS load with just 5 sessions ? and 10 channels ? 100 TPS load ? on an avg each session can handle 4 calls , so 5 sessions can handle only 20 calls ?is my math right ? channel is one per each session as long as it matches to session cnt we should be good. 

grpcChannelCnt | Min sessions | Max sessions | 90th | 95th | 99th
-- | -- | -- | -- | -- | --
10 | 5 | 5 | 10 | 11 | 14
10 | 10 | 10 | 10 | 11 | 16
20 | 10 | 10 | 10 | 11 | 15
35 | 7 | 7 | 10 | 11 | 14
7 | 35 | 35 | 10 | 12 | 15
40 | 40 | 40 | 10 | 11 | 16

**Comment by olavloite** [comment]
The important part here is that one session can handle many transactions during its lifetime, but only one transaction at once. Handling 100TPS that are evenly distributed on 5 sessions is easy, as long as the transactions are short enough not to overlap most of the time. I assume that the 90th, 95th and 99th percentiles in your table depict the (transaction) execution times in milliseconds. If a transaction typically takes 10-15 milliseconds and you are running 100TPS that are evenly distributed, there will normally not be more than 2-3 transactions at any time running parallel (and most of the time only 1 transaction). As long as the number of transactions _running in parallel_ is not exceeding the max number of sessions allowed in the pool, there will be no congestion caused by the session pool.

The same logic goes for the number of channels, but then it applies to the number of gRPC calls running in parallel at any one time, and not the number of transactions. If I understand you correctly, all the transactions in the above example are single use transactions doing one `SELECT` statement. In that case, the number of transactions and number of gRPC calls are equal, and the exact same logic applies to both numbers.
