### ISSUE TITLE
FIREBASE cloud firestore failed to connect in 32bit JVM

### ISSUE THREAD

**Issue by siva461** [googleapis/google-cloud-java#5232]
extracted one of the libraries from mentioned  pom.xml 
grpc-netty-shaded-1.19.0.jar (other versions also)  not supported for 32bit JVM and supports only for 64bit that was mentioned by netty on their website and firestore is using that jar to connect and retrieve data from the cloud.  

The issue is posted to netty team also and they closed it by saying we support 64bit only.

is there a chance to connect firestore using 32bit jvm????

**Comment by wilhuff** [comment]
Firestore does not directly support any platform that gRPC doesn't directly support. grpc-netty relies on pre-built binaries of native code for its networking implementation and only ships binaries for common platforms.

However, just because we're not directly supporting a platform doesn't mean it necessarily won't work. If you're on an alternative platform for which there aren't pre-built binaries you have a few options, and the gRPC team has documented how to do it: https://github.com/grpc/grpc-java/blob/master/SECURITY.md#tls-on-non-android.

You didn't actually say which platform or which java version you're using--only that you're using a 32-bit JVM. Which platform are you using?

**Comment by siva461** [comment]
**WINDOWS 10**

java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

**Comment by wilhuff** [comment]
In that case, your best bet is to build with conscrypt, which does ship binaries for 32-bit Windows.
