### ISSUE TITLE
Cloud Spanner and gax 1.45.0 are incompatible

### ISSUE THREAD

**Issue by sduskis** [googleapis/google-cloud-java#5282]
Cloud Spanner retry testing is blocking an upgrade to gax 1.45.0.  This needs to be fixed, since other clients need the upgrade.  See #5255

**Comment by olavloite** [comment]
Looks to be caused by the change made in https://github.com/googleapis/gax-java/pull/712.

**Comment by olavloite** [comment]
The change mentioned above makes a slight behavioral change that caused the test cases to fail:
* In Gax 1.44: RetrySettings.Builder.setTotalTimeout(Duration.ofMillis(1000)).setRetryableCodes(ImmutableSet.of()) - Will never cause a timeout because there are no retryable codes.
* In Gax 1.45: RetrySettings.Builder.setTotalTimeout(Duration.ofMillis(1000)).setRetryableCodes(ImmutableSet.of()) - Will cause a timeout after 1000 milliseconds, but will never retry.

The total timeout for the test cases has been increased and the test cases pass.
