### ISSUE TITLE
Dialogflow client library for Apple iOS devices

### ISSUE THREAD

**Issue by abhi007tyagi** [googleapis/google-cloud-java#5697]
Is there any V2 library for Apple iOS devices that can be used as client library to communicate with Dialogflow backend from iOS apps similar to old Api.ai Android and iOS library?

If not can it be created?

**Comment by sduskis** [comment]
@abhi007tyagi, this repository is only for Google Cloud Java APIs.  You can see all of he Dialgoflow SDKs here: https://dialogflow.com/docs/sdks, and it looks like there is an iOS client.  If you need further support, please see https://dialogflow.com/support for your options.

I'm going to close this issue, since this issue isn't related to Google Cloud Java clients.

**Comment by abhi007tyagi** [comment]
that is old APi.ai SDK which will be going shutting down in Oct 2019.

**Comment by RakeshKoplodR** [comment]
@abhi007tyagi  @sduskis  I am also looking for V2 library for iOS and Android. I can see library for other languages but not for iOS & Android. Please help me.

**Comment by abhi007tyagi** [comment]
I wrote a library for Android using Java V2. It has complete UI and features like Card, Carousel, Checkboxes, etc. Best thing is you don't need to change code once app is coded. You can control UI from webhook code. Give it a try implementation 'com.tyagiabhinav:androiddialogflowchatbot:0.1.8'

See details here https://medium.com/@abhi007tyagi/android-dialogflow-chatbot-library-6b7b3822e7bc
