### ISSUE TITLE
Clarify BigtableDataClient lifespan best practices.

### ISSUE THREAD

**Issue by bric3** [googleapis/google-cloud-java#6031]
Hi, thanks for your work, however I just need some clarification, on the `BigtableDataClient` usage, but it probably affects other clients though.

The documentation advise to use / limit the lifespan of `BigtableDataClient` within a try-with-resources block, in order to control the resources that the client may use (because this java construct will call the `close` method). 

> try(BigtableDataClient bigtableDataClient = BigtableDataClient.create(bigtableDataSettingsBuilder.build())) {
>  // ..
> }
> [(2)][try-with-resources]

> Note: close() needs to be called on the bigtableDataClient object to clean up resources such as threads. In the example above, try-with-resources is used, which automatically calls close().
[(1)][close]

this usage suggest a one time usage, like for batch jobs. But this doesn't seem appropriate for long running process like a webserver that takes requests and for each request interacts with the `BigtableDataClient`.
Creating this client creates gRPC related resources, without diving too much in the code my guess is that creating then closing repetitively would hurt quite badly the performance in such context. So I think in this case it would be advised to have a `BigtableDataClient` with the same lifespan as the application and invoke the `close` method on the application shutdown.

Is this correct to assume that? Or Is there some other elements to consider? Could you clarify that ?

[close]: https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClient.java#L56-L57
[try-with-resources]: https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClient.java#L102-L112

**Comment by rahulKQL** [comment]
Hi @bric3 

Yes, you are correct. We should definitely reuse the `BigtableDataClient` instance till the end of your application lifecycle.

The Javadoc examples are to showcase the basic use-case of each operation individually that's why it is with `try-with-resources`. In real-world applications, you should consider proper configuration for each operation, which can be done under `BigtableDataSettings#stubSettings()`. eg:
```java
BigtableDataSettings.newBuilder()
        .stubSettings()
        .readRowsSettings()
        .setRetryableCodes(...)
        .setRetrySettings(...)
```
You can find more details on defaults values of each operation at [EnhancedBigtableStubSettings javadoc](https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java#L203-L226).

@igorbernstein2 Please add any points which need to consider.

**Comment by igorbernstein2** [comment]
You are right client creation is expensive and there should only be a single instance. I've updated the docs in #6037.

Thanks for reporting

**Comment by bric3** [comment]
Thank you very much @rahulKQL and @igorbernstein2 for the clarification. (And the quick response !)
