### ISSUE TITLE
CRC error when uploading a specific content to Google cloud storage

### ISSUE THREAD

**Issue by dk823832** [googleapis/google-cloud-java#6386]
The following code results in error message Provided CRC32C "..." doesn't match calculated CRC32C "...":

```
Storage storage;
String bucketName = "bucket";
String blobName = "gtest";
String GOOGLE_CREDENTIALS_SCOPE = "https://www.googleapis.com/auth/cloud-platform";
String APPLICATION_TYPE = "application/octet-stream";
String googleCredentialsJson = null;

ArrayList al = new ArrayList();
al.add(GOOGLE_CREDENTIALS_SCOPE);
String s = String.format("\r\n--__END_OF_PART__--\r\n01234");

googleCredentialsJson = new String ( Files.readAllBytes( Paths.get("google.json") ) );
GoogleCredentials credentials = GoogleCredentials.fromStream(new ByteArrayInputStream(googleCredentialsJson.getBytes()))
                .createScoped(al);
storage = StorageOptions.newBuilder().setCredentials(credentials).build().getService();

BlobId blobId = BlobId.of(bucketName, blobName);
BlobInfo blobInfo = BlobInfo.newBuilder(blobId).setContentType(APPLICATION_TYPE).build();

storage.create(blobInfo, s.getBytes());
```

The issue is reproducible using example programs on Linux:
printf "\r\n--__END_OF_PART__--\r\n01234\n" > rr
java -jar ... com.google.cloud.examples.storage.StorageExample  upload rr bucket

**Comment by athakor** [comment]
@dk823832 I have tried it and able to reproduced.Contrary to your claim `\r\n--__END_OF_PART__--\r\n01234`, `\r\n` It's calling `BufferedWriter.newLine()` which uses the current platform's default line separator (unless you explicitly set the line.separator system property). On Unix systems this will be "\n" so you just add `\n` instead of  `\r\n` error will gets disappear.

`String s = String.format("\n--__END_OF_PART__--\n01234");`

**Comment by dk823832** [comment]
This is not about platform specific line separator. The issue is reproducible on Linux, see my second comment how to reproduce it. Storage API accepts a byte array so it shouldn't matter what content that array contains and it should be able to upload it.

**Comment by dk823832** [comment]
Any news on this issue? Another reproducer on Linux without using String.format:
replace String s = String.format("\n--__END_OF_PART__--\n01234");
with byte s[] = {13, 10, 45, 45, 95, 95, 69, 78, 68, 95, 79, 70, 95, 80, 65, 82, 84, 95, 95, 45, 45, 13, 10, 48, 49, 50, 51, 52};
and storage.create(blobInfo, s.getBytes());
with storage.create(blobInfo, s);

**Comment by fazunenko** [comment]
The problem appears only if the given content includes "--__END_OF_PART__--" string which is used as a part delimiter by com.google.api.client.http.MultipartContent.java
(https://github.com/googleapis/google-http-java-client/blob/master/google-http-client/src/main/java/com/google/api/client/http/MultipartContent.java)

Such content being sent is recognized by the server side as multiple parts and handled in a different way: CRC32C/MD5 calculated only for the first part.

If the content includes "--__END_OF_PART__" (without two dashes at the end) the server will reject:
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
Malformed multipart body.
