### ISSUE TITLE
spanner: client library doesn’t handle a non-existent session error in all places

### ISSUE THREAD

**Issue by skuruppu** [googleapis/google-cloud-java#6422]
We think that if the backend has closed the session, then the client is meant to create a new session and pass that to the user instead of letting this exception bubble up to the user.

```
WARNING: Error during call to readRow. [CONTEXT ratelimit_period="1 MINUTES" ]
com.google.cloud.spanner.SpannerException: NOT_FOUND: io.grpc.StatusRuntimeException: NOT_FOUND: Session not found: projects/<project>/instances/<instance>/databases/<database>/sessions/<session id>
resource_type: "type.googleapis.com/google.spanner.v1.Session"
resource_name: "projects/<project>/instances/<instance>/databases/<database>/sessions/<session id>"
description: "Session does not exist."
```

**Comment by skuruppu** [comment]
@sebright are you able to add the code which resulted in this error so that @olavloite can find the place if any changes need to be make to the error handling?

**Comment by sebright** [comment]
The code that threw the exception read a single row, like this:

```java
Struct row = databaseClient.singleUse().readRow(TABLE_NAME, Key.of(rowId), NON_KEY_COLUMNS);
```

**Comment by olavloite** [comment]
@sebright Is it possible that you used a somewhat older version of the client library? The automatic retry on `SessionNotFoundException` was added on May 13th 2019 so it's not that old, and it should also catch this condition. The [test case here](https://github.com/googleapis/google-cloud-java/blob/2b9bb41e9b3d564c47ac36b40dd977bf2666c0b1/google-cloud-clients/google-cloud-spanner/src/test/java/com/google/cloud/spanner/RetryOnInvalidatedSessionTest.java#L322) covers exactly this case.

If this happened while using a newer version of the client library: In that case it seems that this happened because the error was not recognized as a `SessionNotFoundException` by the client library. Do you have any more information about the exception than you gave above? From what I can see from the log information, that error should have been recognized, so I don't quite understand how this could have happened.

**Comment by sebright** [comment]
@olavloite Great! I wasn't using the latest version, so I'll try upgrading to 1.41.0 and see if the issue disappears.

**Comment by sebright** [comment]
I haven't seen the issue since upgrading to 1.41.0, so I'll close this issue.  Thanks!
