### ISSUE TITLE
RenovateBot unexpectedly modifies values set by Release Please

### ISSUE THREAD

**Issue by suztomo** [googleapis/google-cloud-java#8239]
Example https://github.com/googleapis/google-cloud-java/pull/8237

![image](https://user-images.githubusercontent.com/28604/187320223-aaa778fa-dbac-4805-a828-e079716be7e1.png)

It causes conflicts in pull requests (https://github.com/googleapis/google-cloud-java/pull/8340):

<img width="980" alt="Screen Shot 2022-09-16 at 9 52 29 AM" src="https://user-images.githubusercontent.com/28604/190655213-b87eacc1-f8ff-4a72-8c61-ce5ada72494d.png">

@ddixit14 Would you evaluate whether this is a problem or not?

**Comment by ddixit14** [comment]
@suztomo I think this is because these dependencies have already been released on maven central, and renovate bot is just updating these artifacts with the latest version. And this process is messing up with release-please attempt to update the versions on release. This is mainly due to the lag google-cloud-java has in doing a release for the artifact in the shadow mode. Once we start releasing from monorepo, such conflicts should not occur (hope so). What do you think?

**Comment by suztomo** [comment]
@ddixit14 That's good reasoning. But if RenovateBot is making conflicts in this repository and our versions become inconsistent as per Release Please, we cannot start releasing artifacts from this repository.

Can you configure renovate.json to limit the scope of RenovateBot into only java-shared-config and java-shared-dependencies?

**Comment by suztomo** [comment]
@ddixit14 As discussed, there should be RenovateBot's option to enable "create pull requests only when corresponding item is checked in Dependency Dashboard". Find the option.

If you don't find option and taking 30 mins or more, I'll search it.

**Comment by suztomo** [comment]
Now we have #7649
