### ISSUE TITLE
java-dns and java-notification have empty .OwlBot.yaml

### ISSUE THREAD

**Issue by meltsufin** [googleapis/google-cloud-java#8667]
Unlike every other library, they only have the `api-name:` field, but no copy instructions in the `.OwlBot.yaml`.
This doesn't seem right.
cc/ @suztomo

**Comment by meltsufin** [comment]
What's the story with them? Are they not GAPIC?

**Comment by alicejli** [comment]
Did a bit of digging:
1) `java-notification` looks like it's not a "true" client library as in there's no supporting protos for it. It's actually just a wrapper for Google Cloud Storage to support pub/sub notifications as it seemed the original Storage client didn't support pub/sub. 
It seems like that functionality may have been added in v2.6.1.: https://cloud.google.com/java/docs/reference/google-cloud-storage/latest/history#261httpsgithubcomgoogleapisjava-storagecomparev260v261-2022-04-15 so I have an open question out to yoshi-java to see if that is true. If so, we might want to consider removing this module entirely.

2) `java-dns` is a handwritten REST client because cloudDNS does not support GRPC currently (b/131850399) . It is probably worth a conversation with the DNS team / DEE team to see what the plan should be for this module as it's not something I think we should maintain.

**Comment by alicejli** [comment]
Okay Ben just confirmed that 1. is indeed true (functionality for pub/sub has been added to the main Storage client) and they're planning on turning down https://github.com/googleapis/java-notification next year.
