### ISSUE TITLE
OwlBot postprocessor adds gitignore back

### ISSUE THREAD

**Issue by suztomo** [googleapis/google-cloud-java#8683]
https://github.com/googleapis/google-cloud-java/pull/8682#issuecomment-1290877211

Somehow owlbot-java is trying to add the ".gitignore" file even though the file is excluded in owlbot.py https://github.com/googleapis/google-cloud-java/blob/main/java-dialogflow/owlbot.py#L106

**Comment by lqiu96** [comment]
Took a look at the owlbot and I'm guessing it's due to this line: https://github.com/googleapis/synthtool/blob/48f8857c642792150e2474418b1dbf545c162f8d/docker/owlbot/java/bin/write_templates.sh#L21 called from the entrypoint.sh https://github.com/googleapis/synthtool/blob/48f8857c642792150e2474418b1dbf545c162f8d/docker/owlbot/java/bin/entrypoint.sh#L22

It's before owlbot.py is called so it would have already been included (making the exclusion useless).

I'm guessing we don't need to copy the template/gitignore file over (at least for the monorepo). Tomo can confirm if this is actually the case.

**Comment by lqiu96** [comment]
Looks like dialogflow's `.gitignore` was added back in: https://github.com/googleapis/google-cloud-java/blob/97a095884b05d093ff52feadb8cf9cc0a7a9e3cb/java-dialogflow/.gitignore

Once @suztomo's PR gets merged we should probably re-run the script for deleting the `.gitignore` for all modules.
