### ISSUE TITLE
Revisit the need of DOCLET_VERSION env variable (in Jan 2023)

### ISSUE THREAD

**Issue by suztomo** [googleapis/google-cloud-java#8754]
In Jan 2023, let's revisit the need of if statement and the environment variable to specify doclet version in https://github.com/googleapis/google-cloud-java/pull/8753.

**Comment by lqiu96** [comment]
There is an issue in `java-docfx-doclet` for publishing the doclet artifact to maven central:  https://github.com/googleapis/java-docfx-doclet/issues/105. I think this should be the long term solution so that we don't need to manually update the version in `shared-configs`.

`DOCLET_VERSION` is not needed by default (since `shared-configs` is specifying the version). I kept that in there so that we can publish/update docs by manually setting the `DOCLET_VERSION` env_var in the fusion job. This is so that we can publish/ update docs even if there is an issue in any future version of the doclet. We can manually rollback the doclet version and publish docs without having to wait for shared-configs' doclet version rollback to be released.

**Comment by alicejli** [comment]
I think this property can be removed from `java-shared-config` in general as the `publish_javadoc11.sh` job is now within google3 and doesn't use this property AFAIK. @burkedavison wdyt?

**Comment by burkedavison** [comment]
Agreed. Not used. Can be removed.

**Comment by alicejli** [comment]
Closing this issue as the doclet is managed in `java-shared-config` and the release scripts are in g3 now.
