### ISSUE TITLE
[Recommender] Java SDK lacks recommendations.markDismissed API

### ISSUE THREAD

**Issue by hbui-sc** [googleapis/google-cloud-java#9780]
1. Specify the API: Java recommender
2. OS type and version: MacOS 13.5
3. Java version: 1.8
4. Version(s): 1

#### Steps to reproduce

We cannot use the recommendations.markDismissed API which is in the service definition (https://cloud.google.com/recommender/docs/reference/rpc/google.cloud.recommender.v1#google.cloud.recommender.v1.Recommender.MarkRecommendationDismissed).

Java SDK only supports mark[Claimed|Failed|Succeeded] but lacks the markDismissed() API.

There are [code samples](https://github.com/googleapis/google-cloud-java/blob/main/java-recommender/samples/snippets/generated/com/google/cloud/recommender/v1/recommender/markrecommendationsucceeded/SyncMarkRecommendationSucceeded.java) for markClaimed/Failed/Succeeded. However, the [recommender_service protobuf](https://github.com/googleapis/google-cloud-java/blob/main/java-recommender/proto-google-cloud-recommender-v1/src/main/proto/google/cloud/recommender/v1/recommender_service.proto#L155) lacks of the methods for the markDismissed API.

Could we request to support markDismissed for recommendations?

**Comment by alicejli** [comment]
This has been fixed with https://github.com/googleapis/google-cloud-java/pull/9791. The next release will contain an updated library with this method (~2-3 weeks ish); if you need it sooner, please compile the library directly from the main branch of this repo (`mvn compile && mvn package` will generate a jar that you can use in the interim). Thank you!
